// Mock Data untuk Sistem Peminjaman Alat
import { User, Category, Tool, Borrowing, Notification, ActivityLog } from './types';

// Generate QR Code URL
export const generateQRCode = (data: string): string => {
  return `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(data)}`;
};

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin Utama',
    email: 'admin@sekolah.id',
    role: 'admin',
    phone: '081234567890',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Budi Santoso',
    email: 'budi.petugas@sekolah.id',
    role: 'petugas',
    phone: '081234567891',
    createdAt: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    name: 'Siti Rahmawati',
    email: 'siti.petugas@sekolah.id',
    role: 'petugas',
    phone: '081234567892',
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    id: '4',
    name: 'Ahmad Hidayat',
    email: 'ahmad@siswa.id',
    role: 'peminjam',
    phone: '081234567893',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Dewi Lestari',
    email: 'dewi@siswa.id',
    role: 'peminjam',
    phone: '081234567894',
    createdAt: '2024-02-02T00:00:00Z',
  },
  {
    id: '6',
    name: 'Rina Susanti',
    email: 'rina@siswa.id',
    role: 'peminjam',
    phone: '081234567895',
    createdAt: '2024-02-03T00:00:00Z',
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  { id: '1', name: 'Elektronik', description: 'Peralatan elektronik', icon: 'Laptop', totalItems: 15 },
  { id: '2', name: 'Lab Komputer', description: 'Peralatan lab komputer', icon: 'Monitor', totalItems: 12 },
  { id: '3', name: 'Olahraga', description: 'Peralatan olahraga', icon: 'Dumbbell', totalItems: 20 },
  { id: '4', name: 'Multimedia', description: 'Peralatan multimedia', icon: 'Camera', totalItems: 8 },
  { id: '5', name: 'Lab Fisika', description: 'Peralatan laboratorium fisika', icon: 'FlaskConical', totalItems: 10 },
];

// Mock Tools
export const mockTools: Tool[] = [
  {
    id: '1',
    name: 'Laptop Dell Latitude 5420',
    code: 'LAP-001',
    categoryId: '1',
    categoryName: 'Elektronik',
    description: 'Laptop untuk kegiatan pembelajaran',
    condition: 'baik',
    status: 'tersedia',
    qrCode: generateQRCode('TOOL-LAP-001'),
    location: 'Gudang A - Rak 1',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Proyektor Epson EB-X41',
    code: 'PROJ-001',
    categoryId: '4',
    categoryName: 'Multimedia',
    description: 'Proyektor untuk presentasi',
    condition: 'baik',
    status: 'dipinjam',
    qrCode: generateQRCode('TOOL-PROJ-001'),
    location: 'Gudang B - Rak 2',
    createdAt: '2024-01-16T00:00:00Z',
  },
  {
    id: '3',
    name: 'Kamera Canon EOS 700D',
    code: 'CAM-001',
    categoryId: '4',
    categoryName: 'Multimedia',
    description: 'Kamera DSLR untuk dokumentasi',
    condition: 'baik',
    status: 'tersedia',
    qrCode: generateQRCode('TOOL-CAM-001'),
    location: 'Gudang B - Rak 1',
    createdAt: '2024-01-17T00:00:00Z',
  },
  {
    id: '4',
    name: 'Bola Basket Molten GG7X',
    code: 'BB-001',
    categoryId: '3',
    categoryName: 'Olahraga',
    description: 'Bola basket untuk kegiatan olahraga',
    condition: 'baik',
    status: 'tersedia',
    qrCode: generateQRCode('TOOL-BB-001'),
    location: 'Gudang Olahraga',
    createdAt: '2024-01-18T00:00:00Z',
  },
  {
    id: '5',
    name: 'Mikroskop Olympus CX23',
    code: 'MIC-001',
    categoryId: '5',
    categoryName: 'Lab Fisika',
    description: 'Mikroskop untuk praktikum',
    condition: 'rusak-ringan',
    status: 'maintenance',
    qrCode: generateQRCode('TOOL-MIC-001'),
    location: 'Lab Fisika',
    createdAt: '2024-01-19T00:00:00Z',
  },
  {
    id: '6',
    name: 'Laptop Asus VivoBook',
    code: 'LAP-002',
    categoryId: '1',
    categoryName: 'Elektronik',
    description: 'Laptop cadangan',
    condition: 'baik',
    status: 'tersedia',
    qrCode: generateQRCode('TOOL-LAP-002'),
    location: 'Gudang A - Rak 2',
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '7',
    name: 'Monitor LG 24 inch',
    code: 'MON-001',
    categoryId: '2',
    categoryName: 'Lab Komputer',
    description: 'Monitor untuk lab komputer',
    condition: 'baik',
    status: 'dipinjam',
    qrCode: generateQRCode('TOOL-MON-001'),
    location: 'Lab Komputer',
    createdAt: '2024-01-21T00:00:00Z',
  },
  {
    id: '8',
    name: 'Tripod Manfrotto',
    code: 'TRI-001',
    categoryId: '4',
    categoryName: 'Multimedia',
    description: 'Tripod untuk kamera',
    condition: 'baik',
    status: 'tersedia',
    qrCode: generateQRCode('TOOL-TRI-001'),
    location: 'Gudang B - Rak 1',
    createdAt: '2024-01-22T00:00:00Z',
  },
];

// Mock Borrowings
export const mockBorrowings: Borrowing[] = [
  {
    id: '1',
    borrowerId: '4',
    borrowerName: 'Ahmad Hidayat',
    toolId: '2',
    toolName: 'Proyektor Epson EB-X41',
    toolCode: 'PROJ-001',
    qrCode: generateQRCode('BORROWING-1'),
    borrowDate: '2026-01-08T08:00:00Z',
    dueDate: '2026-01-11T16:00:00Z',
    status: 'active',
    purpose: 'Presentasi tugas akhir',
    approvedBy: 'Budi Santoso',
    approvedAt: '2026-01-08T07:30:00Z',
  },
  {
    id: '2',
    borrowerId: '5',
    borrowerName: 'Dewi Lestari',
    toolId: '7',
    toolName: 'Monitor LG 24 inch',
    toolCode: 'MON-001',
    qrCode: generateQRCode('BORROWING-2'),
    borrowDate: '2026-01-09T09:00:00Z',
    dueDate: '2026-01-12T16:00:00Z',
    status: 'active',
    purpose: 'Kegiatan praktikum',
    approvedBy: 'Siti Rahmawati',
    approvedAt: '2026-01-09T08:30:00Z',
  },
  {
    id: '3',
    borrowerId: '6',
    borrowerName: 'Rina Susanti',
    toolId: '3',
    toolName: 'Kamera Canon EOS 700D',
    toolCode: 'CAM-001',
    qrCode: generateQRCode('BORROWING-3'),
    borrowDate: '2026-01-10T10:00:00Z',
    dueDate: '2026-01-10T15:00:00Z',
    status: 'pending',
    purpose: 'Dokumentasi acara sekolah',
  },
  {
    id: '4',
    borrowerId: '4',
    borrowerName: 'Ahmad Hidayat',
    toolId: '1',
    toolName: 'Laptop Dell Latitude 5420',
    toolCode: 'LAP-001',
    qrCode: generateQRCode('BORROWING-4'),
    borrowDate: '2026-01-05T08:00:00Z',
    dueDate: '2026-01-07T16:00:00Z',
    returnDate: '2026-01-07T15:30:00Z',
    status: 'returned',
    purpose: 'Pengerjaan tugas',
    approvedBy: 'Budi Santoso',
    approvedAt: '2026-01-05T07:45:00Z',
  },
  {
    id: '5',
    borrowerId: '5',
    borrowerName: 'Dewi Lestari',
    toolId: '4',
    toolName: 'Bola Basket Molten GG7X',
    toolCode: 'BB-001',
    qrCode: generateQRCode('BORROWING-5'),
    borrowDate: '2026-01-06T13:00:00Z',
    dueDate: '2026-01-09T16:00:00Z',
    status: 'overdue',
    purpose: 'Latihan basket',
    approvedBy: 'Siti Rahmawati',
    approvedAt: '2026-01-06T12:30:00Z',
  },
  {
    id: '6',
    borrowerId: '6',
    borrowerName: 'Rina Susanti',
    toolId: '6',
    toolName: 'Laptop Asus VivoBook',
    toolCode: 'LAP-002',
    qrCode: generateQRCode('BORROWING-6'),
    borrowDate: '2026-01-09T08:00:00Z',
    dueDate: '2026-01-09T16:00:00Z',
    status: 'rejected',
    purpose: 'Keperluan pribadi',
    rejectedReason: 'Alasan peminjaman tidak sesuai kebijakan',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '2',
    title: 'Pengajuan Peminjaman Baru',
    message: 'Rina Susanti mengajukan peminjaman Kamera Canon EOS 700D',
    type: 'info',
    category: 'peminjaman',
    isRead: false,
    createdAt: '2026-01-10T10:00:00Z',
    link: '/petugas/persetujuan',
  },
  {
    id: '2',
    userId: '4',
    title: 'Peminjaman Disetujui',
    message: 'Peminjaman Proyektor Epson EB-X41 telah disetujui',
    type: 'success',
    category: 'peminjaman',
    isRead: false,
    createdAt: '2026-01-08T07:30:00Z',
  },
  {
    id: '3',
    userId: '5',
    title: 'Pengingat Pengembalian',
    message: 'Bola Basket Molten GG7X sudah melewati batas waktu pengembalian',
    type: 'warning',
    category: 'pengembalian',
    isRead: false,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: '4',
    userId: '6',
    title: 'Peminjaman Ditolak',
    message: 'Pengajuan peminjaman Laptop Asus VivoBook ditolak',
    type: 'error',
    category: 'peminjaman',
    isRead: true,
    createdAt: '2026-01-09T09:00:00Z',
  },
  {
    id: '5',
    userId: '1',
    title: 'Pengembalian Terlambat',
    message: 'Dewi Lestari terlambat mengembalikan Bola Basket Molten GG7X',
    type: 'warning',
    category: 'pengembalian',
    isRead: false,
    createdAt: '2026-01-10T00:00:00Z',
  },
];

// Mock Activity Logs
export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    userId: '2',
    userName: 'Budi Santoso',
    action: 'Menyetujui peminjaman',
    entity: 'Peminjaman',
    entityId: '1',
    details: 'Proyektor Epson EB-X41 untuk Ahmad Hidayat',
    timestamp: '2026-01-08T07:30:00Z',
  },
  {
    id: '2',
    userId: '4',
    userName: 'Ahmad Hidayat',
    action: 'Mengembalikan alat',
    entity: 'Pengembalian',
    entityId: '4',
    details: 'Laptop Dell Latitude 5420',
    timestamp: '2026-01-07T15:30:00Z',
  },
  {
    id: '3',
    userId: '1',
    userName: 'Admin Utama',
    action: 'Menambah alat baru',
    entity: 'Alat',
    entityId: '8',
    details: 'Tripod Manfrotto',
    timestamp: '2026-01-22T10:00:00Z',
  },
  {
    id: '4',
    userId: '3',
    userName: 'Siti Rahmawati',
    action: 'Menyetujui peminjaman',
    entity: 'Peminjaman',
    entityId: '2',
    details: 'Monitor LG 24 inch untuk Dewi Lestari',
    timestamp: '2026-01-09T08:30:00Z',
  },
  {
    id: '5',
    userId: '6',
    userName: 'Rina Susanti',
    action: 'Mengajukan peminjaman',
    entity: 'Peminjaman',
    entityId: '3',
    details: 'Kamera Canon EOS 700D',
    timestamp: '2026-01-10T10:00:00Z',
  },
];
